### ISSUE TITLE
Add Test Cases Using Pytest for All Existing and New Functions

### ISSUE THREAD

**Issue by gkapfham** [GatorGrouper/gatorgrouper#3] opened 2017-10-02 21:14 UTC
Currently, the functions inside of the `gatorgrouper.py` file do not have any test cases associated with them. A good first step would involve adding test cases for the functions that shuffle the list of the students and use the `itertools` package to generate the groups. In particular, it would be useful to have test cases to ensure that the generated groups are never larger than the specified size. Other properties of this algorithm might be more difficult to test as they would involve checking to ensure that the automatically generated groups meet other characteristics like the balancing of the group numbers of the numerical values. (Please see other issues for statements of how these features might work).

**Comment by burrowss** [comment] 2017-10-11 01:08
How is this issue coming along? Checking in since my group's issues are dependent on the test cases

**Comment by bonnettd** [comment] 2017-10-11 01:50
@burrowss Fall break has kind of halted our progress. However we do plan to meet as a team no later than Thursday to discuss what needs to be done and continue building our test suites. Does your group need a fully functional test suites program that tests the entire system, like a test_grouper.py program that includes all of the test suites. Or can you guys work with individual test cases for each of the functions? I guess if you can just give me a description of everything that you need then I can give you an estimated completion time.

**Comment by burrowss** [comment] 2017-10-11 02:09
We're working on #10 and #15 so they will eventually need a fully functioning but we can start by using individual cases. We're currently using lab 2 as a reference to figure out how we want to implement the stuff from our issues so getting don't feel rushed by us, just keep me updated on the progress of the test suite

**Comment by lylet-AC** [comment] 2017-10-12 18:26
Hey, we're issue 10 which involves us writing a testcase specifically for flake8.  Let us know when you guys are ready to talk about integrating our two tasks together!

**Comment by yeeunmariakim** [comment] 2017-10-14 19:02
Here are the functions from my pull request #35 that need testing:

In `create_escaped_string_from_list.py`, the input of the `create_escaped_string_from_list(student_identifiers)` function is a list of strings, and the output of the function should be the concatenation of all the strings in the list, each separated by a newline character. For example, if list = ['Maria', 'Dan', 'Simon'], then the output should be string = "Maria\nDan\nSimon". This should be tested for an empty list, normal list, and large list.

---

Testing the `parse_gatorgrouper_arguments.py` file is a little more involved.
First, you'll need to `import logging`, `import grouping_method`, and `import defaults` into the test cases file to access the logging and grouping method constants.
For the `parse_gatorgrouper_arguments(args)` function, I would suggest four different test cases. Each would have a different starting args value.
1. Input: `args = []`
Output: The output of an empty args (i.e. no command line arguments passed in) should be that all the argument values should be set to their defaults. Specifically,
```
parsed_args = parse_gatorgrouper_arguments(args) 
assert parsed_args.logging_level == logging.ERROR
assert parsed_args.group_size == defaults.DEFAULT_TEAM_SIZE
assert parsed_args.students_file == defaults.DEFAULT_STUDENT_FILE
assert parsed_args.grouping_method == grouping_method.RANDOM
assert parsed_args.absentees == None
```
2. `args = ['--debug', '--students-file', 'students.csv', '--random']`
```
parsed_args = parse_gatorgrouper_arguments(args) 
assert parsed_args.logging_level == logging.DEBUG
assert parsed_args.students_file == 'students.csv'
assert parsed_args.grouping_method == grouping_method.RANDOM
```
3. `args = ['--verbose', '--sudoku']`
```
parsed_args = parse_gatorgrouper_arguments(args) 
assert parsed_args.logging_level == logging.INFO
assert parsed_args.grouping_method == grouping_method.SUDOKU
```
4. `args = ['--absentees', 'maria', '--round-robin', '--group-size', '3']`
```
parsed_args = parse_gatorgrouper_arguments(args) 
assert parsed_args.group_size == 3
assert parsed_args.grouping_method == grouping_method.ROUND_ROBIN
assert parsed_args.absentees == ['maria']
```

For the `check_valid_group_size(group_size, students_list)` function, the parameters are desired group size and a list of students (e.g. ['maria', 'dan', 'simon', 'jesse', 'jon', 'michael', 'jacob', 'kapfhammer']). I would test group sizes of 1, a quarter of the length of students_list, half the length of students_list, and greater than the length of students_list. The expected behavior is that `check_valid_group_size(group_size, students_list)` should return False for group sizes of 1 and greater than the length of students_list and True for group sizes of a quarter and half the length of students_list.

**Comment by dillam** [comment] 2017-10-15 18:10
The only function from issue fourteen that could need testing is the `create_csv` function. It should take the from the spreadsheet and puts them into a csv file with the format.

```
"eltmanm","True","True","True"
"dillam","True","False","False"
```

The function pulls data from the spreadsheet and puts it into a dictionary. From there, it takes the data and formats it so that it can be used to create groups. Finally the formatted data is put into a list and then the list is used to create a csv file.

**Comment by bonnettd** [comment] 2017-10-15 18:13
Function assignments:
Dan: create_escaped_string_from_list, additional tests: duplicate names
Nick: group size validation, display_student_groups, remove_absent_students
Nikki: shuffle_students, display_student_identifiers
Jeff: parse_gatorgrouper_arguments, display_diagnostics

Undecided: proper categorization

**Comment by burrowss** [comment] 2017-10-15 19:11
My group has a linting tool that we will need to add to the testing suite when you guys are ready. It is just about done so let me know when we can combine our code

**Comment by cerdamejiaj** [comment] 2017-10-15 19:19
@burrowss we are working on the test suite, but we can not fully complete them until the rest of the team managers tell us what they want us to test for their functions. Hopefully, they let us know by end of the day.

**Comment by millinj2** [comment] 2017-10-15 22:01
For issue #12 
Inputs: List of lists of students ` [[student1, 0, 1,0], [student2 ,0, 1, 1], [student3, 1, 1, 0]]` and list of absent students `[student2]`

Output: List of lists of students excluding absent students `[[student1, 0, 1, 0], [student3, 1, 1, 0]]`

**Comment by bonnettd** [comment] 2017-10-16 01:19
@millinj2 Could you please specify the function that you are referring to?

**Comment by millinj2** [comment] 2017-10-16 01:47
@bonnettd yes sorry its remove_absent_students():

`def remove_absent_students(absentee_list, list_of_student_lists):
    list_of_student_lists_copy = list_of_student_lists[:]
    for name in absentee_list:
        for student_list in list_of_student_lists :
            if student_list[0] == name :
                list_of_student_lists_copy.remove(student_list)
    return list_of_student_lists_copy
`

**Comment by bonnettd** [comment] 2017-10-16 01:48
@millinj2 Thank you!

**Comment by bonnettd** [comment] 2017-10-16 02:21
@dillam In regards to the create_csv function, what is the name of the file that the function reads from to get the data? Also, is the output of the function one big list of lists where every element is a string? For example in the output that you described above: "eltmanm","True","True","True"
                                                                             "dillam","True","False","False"
Lets say that the outputted list is called output_list, would "eltmanm","True","True","True" be output_list[0] and would  "dillam","True","False","False" be output_list[1]?

**Comment by bonnettd** [comment] 2017-10-16 03:48
@burrowss Just to give you a little status update: My group has completed most of the test suites for the program. We still have a few functions that are being completed so until they're completed we cannot fully complete or test our test suites. I am hoping to deliver a functioning test suites file to you as soon as possible tomorrow. I have spoken multiple times with your group member Austin, and we both know what we need from each other so no need to worry about his issue.

**Comment by Andre-Bryan** [comment] 2017-10-16 04:10
I also need them to run the pytest-coverage calculate and report

**Comment by delgrecoj** [comment] 2017-10-16 05:01
`shuffle_students` takes a list and randomly shuffles it, returning the shuffled list.
`group_random` takes a list of the student responses and a desired group size, and groups the responses into the groups randomly, logging the scores and handling the last group as discussed in #40.
`group_rrobin` takes a list of the student responses and a desired group size, and groups the responses into the groups, by randomly selecting an ordering of the response columns to look at, and dropping one response in each group if the response was a "yes", and repeating for the other columns.  Remaining responses that weren't caught already are then distributed in a similar round-robin manner, until the list of remaining responses is exhausted, and the scores are logged and the groups are returned.
`score_group` takes a group of responses and scores them according to @ZachAndrews98's comment in #13, returning the score.
`score_groups` receives multiple groups and feeds each through the prior function, returning the scores and an average.
`read_student_file` takes in a filepath to a CSV file, and parses that file, returning a list of responses, which are lists themselves, performing some simple conversion into Python boolean datatypes.
`rebalance` takes in the generated groups, scores, and average score, and switches the highest scoring response with the lowest, in an effort to balance the groups better.

**Comment by toccinAC** [comment] 2017-10-16 15:21
@millinj2 Hey I am currently writing the test for your function. I am just wondering where in the overall program does it interact with the list of students, because I don't see any other function that calls it.

**Comment by dillam** [comment] 2017-10-16 17:47
@bonnettd The output of the function is a csv file called `data.csv`.  The name of the file it reads from is a google sheet called `Compsci280 Lab4 Survey Results`, the link for the spreadsheet is [here](https://docs.google.com/a/allegheny.edu/spreadsheets/d/1UkQDA5v0DWPxoKPUqOVQir6cbzX89o64EVUxMgbEyec/edit?usp=sharing). The list is only used to make the csv file.

**Comment by millinj2** [comment] 2017-10-16 18:37
@toccinAC @yeeunmariakim Maria didn't you say your team was working on the command line arguments to read in the csv file for issue 12?

**Comment by yeeunmariakim** [comment] 2017-10-16 18:42
@millinj2 no, issue 12 never communicated with me a need for a command line argument. I added a command line argument to read in a list of absent students.

**Comment by yeeunmariakim** [comment] 2017-10-16 18:43
@toccinAC it shouldn’t matter whether the function was called to be able to test that function. If I recall correctly, @delgrecoj said he would be including the use of that function.

**Comment by toccinAC** [comment] 2017-10-16 19:17
Thank you I had already made the test case, I was just looking into the program to understand it better and never saw it called. Thank you for clarifying.

**Comment by cerdamejiaj** [comment] 2017-10-16 19:28
hey, @yeeunmariakim  I'm doing the test cases for arse_gatorgrouper_arguments(args). I'm getting two errors when I'm running them.
     
  `FileNotFoundError: [Errno 2] No such file or directory: 'students.csv'`
  `FileNotFoundError: [Errno 2] No such file or directory: 'students.txt'`
In the gatorgrouper I only see the students.txt but I don't see the students.csv

**Comment by cerdamejiaj** [comment] 2017-10-16 19:43
@delgrecoj we are creating the test cases for your functions but we can't actually test them until they are in master.

**Comment by delgrecoj** [comment] 2017-10-16 20:03
has just been merged.

**Comment by Andre-Bryan** [comment] 2017-10-17 00:56
anytime estimate on the test suites?

**Comment by cerdamejiaj** [comment] 2017-10-17 01:03
@Andre-Bryan they should in test folder now. Is called test_gatorgrouper.py. Things might be added in the next few minutes.

**Closed** 2017-10-17 15:30 UTC
Labels: testing, tools
