### ISSUE TITLE
Specify Skill Levels for Categories and then Customize Group Assignment

### ISSUE THREAD

**Issue by gkapfham** [GatorGrouper/gatorgrouper#14] opened 2017-10-02 21:51 UTC
As mentioned in Issue #13, the current algorithm for assigning the groups only involves random number generation. While it might be useful to assign students to groups based on categories, it could also be useful to assign "skill levels" for the different categories. This might allow the tool to better follow some of the [best practices](http://www4.ncsu.edu/unity/lockers/users/f/felder/public/Papers/Oakley-paper(JSCL).pdf) for assigning students to teams. Perhaps it might be possible to assign numerical values to the input students according to a Likert Scale that ranges from the whole numbers one and five?

**Comment by eltmanm** [comment] 2017-10-03 20:13
The Mikes will be parsing together data on the collection method and putting that data into a file for the program to read.

**Comment by dillam** [comment] 2017-10-04 17:43
I made a google form to determine the skill level of the students. [This](https://goo.gl/forms/DuNj7ZrjJXcJO3wL2) is the link for the form.

**Comment by Andre-Bryan** [comment] 2017-10-04 17:50
https://pypi.python.org/pypi/pgsheets/0.0.1 pgsheets documentation

**Comment by dillam** [comment] 2017-10-04 17:51
Another library we can look at [here](https://docs.python.org/2/library/csv.html)

**Comment by eltmanm** [comment] 2017-10-04 17:51
And i have a spreadsheet designed to output the results from the survey. this is it: https://docs.google.com/a/allegheny.edu/spreadsheets/d/1UkQDA5v0DWPxoKPUqOVQir6cbzX89o64EVUxMgbEyec/edit?usp=sharing

**Comment by eltmanm** [comment] 2017-10-04 18:19
#16 please take a look at the above files and let us know what needs added, removed, reformatted, etc.

**Comment by eltmanm** [comment] 2017-10-06 17:37
This seems like a reasonable method to use so as to use constantly updated information. #12 could make use of an additional column in the spreadsheet so as to allow the instructor to mark a student absent as is, and the program would likely put this information in your chunk of the program.
https://www.twilio.com/blog/2017/02/an-easy-way-to-read-and-write-to-a-google-spreadsheet-in-python.html

**Comment by dillam** [comment] 2017-10-13 00:52
At the group leader meeting we decided that it would be better if the questions we asked in the google form were yes or no rather than a scale from 1 to 5. I just made the changes to the form.

**Comment by dillam** [comment] 2017-10-13 00:55
@eltmanm can you commit the work you have done so far to a branch off of the branch for this issue?

**Comment by eltmanm** [comment] 2017-10-13 17:50
so i tried to work around the installation errors to download a package we need to read from sheets to the console (gspread, as i've been able to find alternatives), and it gave me the same errors as before, as well as a confirmation that the issue is lack of admin access for our python library storage. there is a copy of the text from the terminal in the latest push, as ERRORS.txt I will discuss this with Professor Kapfhammer around the end of class

**Comment by eltmanm** [comment] 2017-10-13 17:55
also, i've fixed the sheets/form to pull from the new format when taking responses

**Comment by eltmanm** [comment] 2017-10-13 18:37
I HAVE THE PACKAGES INSTALLED NOW< WILL BE WORKING ON CSV SAVING, AND WHAT NOT< THEN WILL NEED TO COORDINATE WITH OTHERS TO ASSIST IN HOW TO WORK WITH ANY OTHER FILE OPERATIONS WE CAN WORK WITH

**Comment by eltmanm** [comment] 2017-10-13 18:43
And now the latest commit is the progress i've got thus far. Will likely come back to it later tonight

**Comment by dillam** [comment] 2017-10-14 19:30
The program now takes the data from the google sheet and inputs the data into a csv.

**Comment by dillam** [comment] 2017-10-16 04:14
The branch was merged into master. I am closing the issue.

**Closed by dillam** 2017-10-16 04:14 UTC
Labels: enhancement, please examine
